#!/bin/bash
ulimit -n 131072
ulimit -l 82000
if [ "${VARNISH_MEMORY}" == "" ]; then
  VARNISH_MEMORY = "1G"
fi
varnishd -f /etc/varnish/default.vcl -C -n /tmp
exec varnishd -j none -F -f /etc/varnish/default.vcl \
     -s malloc,${VARNISH_MEMORY} -a 0.0.0.0:81 \
     -T 0.0.0.0:6082 \
     -p http_req_hdr_len=16384 -p http_resp_hdr_len=16384 ${VARNISH_DAEMON_OPTS}
